apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dlb-worker
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - dlb
  selector:
    matchLabels:
      app: dlb-worker
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
